"""Thin facade — all agents orchestration logic lives in application/agents/agents_service.py."""
from app.application.agents.agents_service import (  # noqa: F401
    PlannerV2Service,
    _build_prompt,
    _build_single_web_subquery_context,
    _clean_query,
    _collect_context_legacy,
    _do_temporal_web_search_legacy,
    _do_web_search,
    _do_web_search_legacy,
    _get_web_search_result,
    _is_strict_web_only_query,
    _run_auto_skills,
    _short,
    _strip_frontend_project_context_legacy,
    _wants_explicit_datetime_answer,
    logger,
    run_agent,
    run_agent_stream,
)
