"""Thin facade — all autopipeline logic lives in application/autopipeline/autopipeline_service.py."""
from app.application.autopipeline.autopipeline_service import (  # noqa: F401
    DATA_DIR,
    DB_PATH,
    _TICK_INTERVAL,
    _connect,
    _execute_task,
    _init_db,
    _tick,
    create_pipeline,
    delete_pipeline,
    get_pipeline,
    get_pipeline_logs,
    list_pipelines,
    run_pipeline_now,
    scheduler_status,
    start_scheduler,
    stop_scheduler,
    update_pipeline,
)
