"""Thin facade — all core state DB logic lives in infrastructure/db/elira_memory_sqlite.py."""
from app.infrastructure.db.elira_memory_sqlite import (  # noqa: F401
    DB_PATH,
    _VALID_TABLES,
    _chat_row,
    _connect,
    _ensure_column,
    _table_exists,
    add_message,
    count_chats,
    count_messages,
    create_chat,
    delete_chat,
    get_messages,
    init_db,
    list_chats,
    rename_chat,
    set_chat_memory_saved,
    set_chat_pinned,
    update_chat,
)
