"""Thin facade — all persona service logic lives in application/persona/persona_service.py."""
from app.application.persona.persona_service import (  # noqa: F401
    _append_trait,
    _audit,
    _bootstrap_if_needed,
    _candidate_event_stats,
    _connect,
    _contradiction_score,
    _ensure_tables,
    _extract_signals,
    _get_previous_version,
    _json_dumps,
    _json_loads,
    _maybe_promote_candidates,
    _promote_candidate,
    _row_to_version,
    _update_model_calibration,
    _utc_now,
    build_persona_prompt,
    get_model_calibration,
    get_persona_status,
    get_persona_version,
    init_persona_store,
    list_persona_candidates,
    observe_dialogue,
    rollback_persona,
)
