"""Thin facade — all plugin system logic lives in infrastructure/plugins/plugin_system.py."""
from app.infrastructure.plugins.plugin_system import (  # noqa: F401
    PLUGINS_DIR,
    _CONFIG_FILE,
    _get_plugin_config,
    _load_config,
    _save_config,
    _set_plugin_config,
    check_triggers,
    disable_plugin,
    enable_plugin,
    fire_hook,
    get_plugin_info,
    list_plugins,
    load_plugins,
    reload_plugins,
    run_plugin,
    run_triggered,
    update_plugin_settings,
)
