"""Thin facade — all Telegram bot logic lives in infrastructure/integrations/telegram_service.py."""
from app.infrastructure.integrations.telegram_service import (  # noqa: F401
    DB_PATH,
    TG_API,
    _connect,
    _get_config,
    _handle_command,
    _init_db,
    _is_user_allowed,
    _log_message,
    _poll_loop,
    _process_message,
    _register_user,
    _send_message,
    _send_typing,
    _set_config,
    _tg_request,
    get_telegram_config,
    get_telegram_log,
    list_telegram_users,
    start_telegram_bot,
    stop_telegram_bot,
    telegram_bot_status,
    test_telegram_connection,
    toggle_user_access,
    update_telegram_config,
)
