"""Thin facade — all tool registry logic lives in application/tools/tool_registry.py."""
from app.application.tools.tool_registry import (  # noqa: F401
    DB_PATH,
    _BUILTIN_SEEDED,
    _CREATE_SQL,
    _conn,
    _init_db,
    _noop_handler,
    _now,
    _row_to_dict,
    delete_tool,
    execute_tool,
    get_tool,
    list_tools_with_schemas,
    register_tool,
    register_tool_from_dict,
    seed_builtin_tools,
    update_tool,
    validate_tool_args,
)
