"""Compatibility facade for chat provenance guard policy."""

from __future__ import annotations

from app.application.chat.provenance_guard import (
    BARE_URL_RE,
    FIRST_PERSON_NAME_RE,
    INLINE_SOURCE_CITATION_RE,
    MARKDOWN_SOURCE_LINK_RE,
    MULTISPACE_RE,
    PERSONAL_NAME_QUESTION_RE,
    PROVENANCE_QUESTION_RE,
    RAG_MARKER_LINE_RE,
    RAW_MARKER_RE,
    SENTENCE_SPLIT_RE,
    SOURCE_LEAD_REPLACEMENTS,
    SOURCE_LINE_RE,
    TECHNICAL_HEADER_RE,
    TECHNICAL_TOKEN_RE,
    UNWANTED_SOURCE_SENTENCE_RE,
    WHITESPACE_BEFORE_PUNCT_RE,
    _normalize_whitespace,
    _rewrite_direct_personal_facts,
    _rewrite_natural_provenance,
    _strip_raw_markers,
    _strip_technical_source_phrases,
    guard_provenance_response,
    is_provenance_question,
)

__all__ = [
    "BARE_URL_RE",
    "FIRST_PERSON_NAME_RE",
    "INLINE_SOURCE_CITATION_RE",
    "MARKDOWN_SOURCE_LINK_RE",
    "MULTISPACE_RE",
    "PERSONAL_NAME_QUESTION_RE",
    "PROVENANCE_QUESTION_RE",
    "RAG_MARKER_LINE_RE",
    "RAW_MARKER_RE",
    "SENTENCE_SPLIT_RE",
    "SOURCE_LEAD_REPLACEMENTS",
    "SOURCE_LINE_RE",
    "TECHNICAL_HEADER_RE",
    "TECHNICAL_TOKEN_RE",
    "UNWANTED_SOURCE_SENTENCE_RE",
    "WHITESPACE_BEFORE_PUNCT_RE",
    "_normalize_whitespace",
    "_rewrite_direct_personal_facts",
    "_rewrite_natural_provenance",
    "_strip_raw_markers",
    "_strip_technical_source_phrases",
    "guard_provenance_response",
    "is_provenance_question",
]
