import type { CodeAgentToolCall } from "../api/codeAgent";

export type UserTurnData = { kind: "user"; id: string; text: string };

export type PendingApproval = {
  approvalId: string;
  tool: string;
  arguments: Record<string, unknown>;
  waitedS?: number;
  resolving?: boolean;
};

export type AgentTurnData = {
  kind: "agent";
  id: string;
  toolCalls: CodeAgentToolCall[];
  text: string;
  running: boolean;
  activeTool?: string;
  error?: string | null;
  stopReason?: string;
  runId?: string;
  resumable?: boolean;
  pendingApproval?: PendingApproval;
  /** Live count of tokens generated by the local model this turn, summed across
   *  steps from `usage` stream events. */
  genTokens?: number;
  /** Most recent generation speed (tokens/sec) reported by the server. */
  tokensPerSecond?: number;
};

export type FileEntry = {
  name: string;
  isImage: boolean;
  url?: string;
  status: "uploading" | "saved" | "error";
};

export type FilesTurnData = { kind: "files"; id: string; files: FileEntry[] };

export type Turn = UserTurnData | AgentTurnData | FilesTurnData;
