import type { AnswerMediaItem, AnswerStatus, CodeAgentToolCall, CompletionStatus, CriterionState } from "../api/codeAgent";

export type UserTurnData = { kind: "user"; id: string; text: string };

export type AgentTurnData = {
  kind: "agent";
  id: string;
  toolCalls: CodeAgentToolCall[];
  text: string;
  /** Model reasoning streamed on the separate `reasoning_delta` channel when the
   *  «Рассуждение» toggle is on. Shown in a collapsible block, kept out of the
   *  answer text and out of conversation history. */
  reasoning?: string;
  /** Coarse runtime phase only. Raw chain-of-thought is never stored here. */
  brainPhase?: "planning" | "execution" | "verification";
  /** Compact digest of facts the discovery tools established this turn (which
   *  files exist, function signatures, command output). Carried into the next
   *  turn's conversation_history as an authoritative grounding block so the model
   *  answers factual follow-ups from fact instead of confabulating. Not rendered
   *  in the answer bubble. */
  establishedFacts?: string;
  /** Verbatim raw output of this turn's recent grounding tools; carried (for the
   *  LAST agent turn only) into the next turn so a follow-up reads the real text,
   *  not just the compact facts summary. */
  recentToolOutput?: string;
  /** Runtime-validated media discovered by tools for this answer. */
  media?: AnswerMediaItem[];
  running: boolean;
  activeTool?: string;
  error?: string | null;
  stopReason?: string;
  /** Factual-answer quality, separate from transport health and task criteria. */
  answerStatus?: AnswerStatus;
  /** Task-completion axis — SEPARATE from runtime success. "confirmed" = every
   *  success criterion proven by a verifier; UI shows "solved" only on this. */
  completionStatus?: CompletionStatus;
  /** Per-criterion verification state for the task panel. */
  criteria?: CriterionState[];
  runId?: string;
  resumable?: boolean;
  /** Live count of tokens generated by the local model this turn, summed across
   *  steps from `usage` stream events. */
  genTokens?: number;
  /** Most recent generation speed (tokens/sec) reported by the server. */
  tokensPerSecond?: number;
};

export type FileEntry = {
  name: string;
  isImage: boolean;
  url?: string;
  status: "uploading" | "saved" | "error" | "attached";
};

export type FilesTurnData = { kind: "files"; id: string; files: FileEntry[] };

export type Turn = UserTurnData | AgentTurnData | FilesTurnData;
