import type { CodeAgentToolCall } from "../api/codeAgent";

export type UserTurnData = { kind: "user"; id: string; text: string };

export type PendingApproval = {
  approvalId: string;
  tool: string;
  arguments: Record<string, unknown>;
  waitedS?: number;
  resolving?: boolean;
};

export type PendingQuestion = {
  questionId: string;
  question: string;
  options: string[];
  waitedS?: number;
  answering?: boolean;
};

export type AgentTurnData = {
  kind: "agent";
  id: string;
  toolCalls: CodeAgentToolCall[];
  text: string;
  /** Model reasoning streamed on the separate `reasoning_delta` channel when the
   *  «Рассуждение» toggle is on. Shown in a collapsible block, kept out of the
   *  answer text and out of conversation history. */
  reasoning?: string;
  /** Compact digest of facts the discovery tools established this turn (which
   *  files exist, function signatures, command output). Carried into the next
   *  turn's conversation_history as an authoritative grounding block so the model
   *  answers factual follow-ups from fact instead of confabulating. Not rendered
   *  in the answer bubble. */
  establishedFacts?: string;
  /** Verbatim raw output of this turn's recent grounding tools; carried (for the
   *  LAST agent turn only) into the next turn so a follow-up reads the real text,
   *  not just the compact facts summary. */
  recentToolOutput?: string;
  running: boolean;
  activeTool?: string;
  error?: string | null;
  stopReason?: string;
  runId?: string;
  resumable?: boolean;
  pendingApproval?: PendingApproval;
  pendingQuestion?: PendingQuestion;
  /** Live count of tokens generated by the local model this turn, summed across
   *  steps from `usage` stream events. */
  genTokens?: number;
  /** Most recent generation speed (tokens/sec) reported by the server. */
  tokensPerSecond?: number;
};

export type FileEntry = {
  name: string;
  isImage: boolean;
  url?: string;
  status: "uploading" | "saved" | "error" | "attached";
};

export type FilesTurnData = { kind: "files"; id: string; files: FileEntry[] };

export type Turn = UserTurnData | AgentTurnData | FilesTurnData;
